### ISSUE TITLE
Adding and removing priority queues.

### ISSUE THREAD

**Issue by varad** [marianobarrios/linked-blocking-multi-queue#1]
Hi, 

I'm testing your library and it looks good. But I found some issues when adding/removing priority queues.

I wrote tests for those issues and proposed a fix. Please review my fork and let me know what you think: https://github.com/varad/linked-blocking-multi-queue/commit/ec70d7c106c1f0f5ce1be95c63b6a07b444a6bb7

Issues:
1. removeQueue - When removing a subqueue of the same priority, the "round robin pointer to the next subqueue" went index out of bound. The check was there but we have to remove the subqueue first.
2. addSubQueue - the subqueue was added multiple times. Also, you have to stop the loop after adding an item - if you don't you get ConcurrentModificationException
3. do not leave a priority subqueue empty - otherwise, you'll get "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0" when calling getNextSubQueue

**Comment by marianobarrios** [comment]
Thanks Radek! Looks good to me, feel free to create a pull request.

**Comment by varad** [comment]
Thanks. I created a pull request.

**Comment by varad** [comment]
Pull request have been merged. 

One more question before closing the issue - are you going to release it? Thanks.

**Comment by marianobarrios** [comment]
Yes, just [done](http://search.maven.org/#artifactdetails%7Ccom.github.marianobarrios%7Clinked-blocking-multi-queue%7C0.3.0%7C) (note that the maven coordinates changed).
