### ISSUE TITLE
NullPointer during take/poll operations

### ISSUE THREAD

**Issue by mbettiol** [marianobarrios/linked-blocking-multi-queue#29]
Hi,
the library throws NullPointerException in multiple Producers/Consumers scenario.
It seems like totalCount is higher than the effective number of messages available in subqueues causing subQueueSelection.getNext() to return null

Test scenario
Producer (10 threads)/Consumer(20 threads) perform fast operations (milliseconds).
Consumers are created before producers and attached to the LinkedBlockingQueue
Just 1 subqueue is used for the test: "test.p1message"

I will try to investigate further.
At the moment I can share the following debug screen.
Used 0.4.0

![image](https://user-images.githubusercontent.com/1444806/190852041-a3f145e8-db33-4c15-85a5-3416e5a684ab.png)
```

 -java.lang.NullPointerException: null
	at lbmq.LinkedBlockingMultiQueue$SubQueue.access$500(LinkedBlockingMultiQueue.java:475)
	at lbmq.LinkedBlockingMultiQueue.take(LinkedBlockingMultiQueue.java:362)
```

Regards, Marco

**Comment by marianobarrios** [comment]
Hi Marco, thanks for your report. Would you have some test case or code fragment with which I could reproduce the problem?

**Comment by mbettiol** [comment]
Hi Mariano,
it was an issue caused by "enable(true)" immediatelly after adding a newSubQueue: this caused a wrong totalSize.
I pushed a pull request to make enable/disable idempotent and therefore protect againts misusage.

Regards,
 Marco

**Comment by marianobarrios** [comment]
Fix released.
