### ISSUE TITLE
Mixed Queues

### ISSUE THREAD

**Issue by magicprinc** [marianobarrios/linked-blocking-multi-queue#31]
Hello!

Thank You very much for such a great project!

I have a question:

I need to mix a usual Blocking Queue with DelayQueue.
The usage case is quite obvious: the worker thread gets an element from Queue, but sometimes there is a problem (e.g. remote REST service is not responding), so the worker puts the element to DelayQueue with ever-increasing delay, to retry later.

So there are two queues: "main" queue and delay queue.

Now I read them after one another, and it looks ugly.

My dream is: mix them in one blocking-multi-queue with one beautiful block on get element, without spin loops and extra delay in consumption.

**Comment by marianobarrios** [comment]
I don't think this is possible, as it would require adding DelayQueue logic to this class, which would be significantly out of scope. In any case, why cannot you just use a DelayQueue for all elements, just using zero delay in some cases?

**Comment by magicprinc** [comment]
This is an interesting idea!
I will test it!
