### ISSUE TITLE
Consider changing the license

### ISSUE THREAD

**Issue by sdoeringNew** [marianobarrios/linked-blocking-multi-queue#34]
A BSD license may be deterrend.

Off course, it is your choice.

I (we) sadly can not use the lbmq because of BSD.
Consider using MIT or Apache License.

**Comment by marianobarrios** [comment]
Hi sdoeringNew,

May I ask why? The 2-clause BSD license is minimal, and essentially equivalent to the MIT one. The Apache License, on the other hand, has _more_ restrictions than the other two, which should make it less preferable to users, not the other way around...

**Comment by sdoeringNew** [comment]
That's a good question. After reading into it, your are right and MIT is almost identical to 2-clause BSD.
So we can use it. Cool. 👍
