### ISSUE TITLE
Custom SubQueueSelection

### ISSUE THREAD

**Issue by stik79** [marianobarrios/linked-blocking-multi-queue#60]
Trying to use a custom SubQueueSelection (implements LinkedBlockingMultiQueue.SubQueueSelection<K,E> ) however it seems impossible due to PriorityGroups being package private?

This makes implementing setPriorityGroups impossible (unless I'm missing something).

Similarly cannot extend DefaultSubQueueSelection for the same reason.

**Comment by marianobarrios** [comment]
Thanks for the report and sorry for the delay. Fixed in 0.7.0.
